import { Identifier } from "../../ast";

/**
 * named css colors - https://www.w3.org/wiki/CSS/Properties/color/keywords
 * generated by css-color-names.py
 */
export class CssNamedColor extends Identifier {
  static aliceblue = new CssNamedColor("aliceblue", "#f0f8ff");
  static antiquewhite = new CssNamedColor("antiquewhite", "#faebd7");
  static aqua = new CssNamedColor("aqua", "#00ffff");
  static aquamarine = new CssNamedColor("aquamarine", "#7fffd4");
  static azure = new CssNamedColor("azure", "#f0ffff");
  static beige = new CssNamedColor("beige", "#f5f5dc");
  static bisque = new CssNamedColor("bisque", "#ffe4c4");
  static black = new CssNamedColor("black", "#000000");
  static blanchedalmond = new CssNamedColor("blanchedalmond", "#ffebcd");
  static blue = new CssNamedColor("blue", "#0000ff");
  static blueviolet = new CssNamedColor("blueviolet", "#8a2be2");
  static brown = new CssNamedColor("brown", "#a52a2a");
  static burlywood = new CssNamedColor("burlywood", "#deb887");
  static cadetblue = new CssNamedColor("cadetblue", "#5f9ea0");
  static chartreuse = new CssNamedColor("chartreuse", "#7fff00");
  static chocolate = new CssNamedColor("chocolate", "#d2691e");
  static coral = new CssNamedColor("coral", "#ff7f50");
  static cornflowerblue = new CssNamedColor("cornflowerblue", "#6495ed");
  static cornsilk = new CssNamedColor("cornsilk", "#fff8dc");
  static crimson = new CssNamedColor("crimson", "#dc143c");
  static cyan = new CssNamedColor("cyan", "#00ffff");
  static darkblue = new CssNamedColor("darkblue", "#00008b");
  static darkcyan = new CssNamedColor("darkcyan", "#008b8b");
  static darkgoldenrod = new CssNamedColor("darkgoldenrod", "#b8860b");
  static darkgray = new CssNamedColor("darkgray", "#a9a9a9");
  static darkgreen = new CssNamedColor("darkgreen", "#006400");
  static darkgrey = new CssNamedColor("darkgrey", "#a9a9a9");
  static darkkhaki = new CssNamedColor("darkkhaki", "#bdb76b");
  static darkmagenta = new CssNamedColor("darkmagenta", "#8b008b");
  static darkolivegreen = new CssNamedColor("darkolivegreen", "#556b2f");
  static darkorange = new CssNamedColor("darkorange", "#ff8c00");
  static darkorchid = new CssNamedColor("darkorchid", "#9932cc");
  static darkred = new CssNamedColor("darkred", "#8b0000");
  static darksalmon = new CssNamedColor("darksalmon", "#e9967a");
  static darkseagreen = new CssNamedColor("darkseagreen", "#8fbc8f");
  static darkslateblue = new CssNamedColor("darkslateblue", "#483d8b");
  static darkslategray = new CssNamedColor("darkslategray", "#2f4f4f");
  static darkslategrey = new CssNamedColor("darkslategrey", "#2f4f4f");
  static darkturquoise = new CssNamedColor("darkturquoise", "#00ced1");
  static darkviolet = new CssNamedColor("darkviolet", "#9400d3");
  static deeppink = new CssNamedColor("deeppink", "#ff1493");
  static deepskyblue = new CssNamedColor("deepskyblue", "#00bfff");
  static dimgray = new CssNamedColor("dimgray", "#696969");
  static dimgrey = new CssNamedColor("dimgrey", "#696969");
  static dodgerblue = new CssNamedColor("dodgerblue", "#1e90ff");
  static firebrick = new CssNamedColor("firebrick", "#b22222");
  static floralwhite = new CssNamedColor("floralwhite", "#fffaf0");
  static forestgreen = new CssNamedColor("forestgreen", "#228b22");
  static fuchsia = new CssNamedColor("fuchsia", "#ff00ff");
  static gainsboro = new CssNamedColor("gainsboro", "#dcdcdc");
  static ghostwhite = new CssNamedColor("ghostwhite", "#f8f8ff");
  static goldenrod = new CssNamedColor("goldenrod", "#daa520");
  static gold = new CssNamedColor("gold", "#ffd700");
  static gray = new CssNamedColor("gray", "#808080");
  static green = new CssNamedColor("green", "#008000");
  static greenyellow = new CssNamedColor("greenyellow", "#adff2f");
  static grey = new CssNamedColor("grey", "#808080");
  static honeydew = new CssNamedColor("honeydew", "#f0fff0");
  static hotpink = new CssNamedColor("hotpink", "#ff69b4");
  static indianred = new CssNamedColor("indianred", "#cd5c5c");
  static indigo = new CssNamedColor("indigo", "#4b0082");
  static ivory = new CssNamedColor("ivory", "#fffff0");
  static khaki = new CssNamedColor("khaki", "#f0e68c");
  static lavenderblush = new CssNamedColor("lavenderblush", "#fff0f5");
  static lavender = new CssNamedColor("lavender", "#e6e6fa");
  static lawngreen = new CssNamedColor("lawngreen", "#7cfc00");
  static lemonchiffon = new CssNamedColor("lemonchiffon", "#fffacd");
  static lightblue = new CssNamedColor("lightblue", "#add8e6");
  static lightcoral = new CssNamedColor("lightcoral", "#f08080");
  static lightcyan = new CssNamedColor("lightcyan", "#e0ffff");
  static lightgoldenrodyellow = new CssNamedColor(
    "lightgoldenrodyellow",
    "#fafad2"
  );
  static lightgray = new CssNamedColor("lightgray", "#d3d3d3");
  static lightgreen = new CssNamedColor("lightgreen", "#90ee90");
  static lightgrey = new CssNamedColor("lightgrey", "#d3d3d3");
  static lightpink = new CssNamedColor("lightpink", "#ffb6c1");
  static lightsalmon = new CssNamedColor("lightsalmon", "#ffa07a");
  static lightseagreen = new CssNamedColor("lightseagreen", "#20b2aa");
  static lightskyblue = new CssNamedColor("lightskyblue", "#87cefa");
  static lightslategray = new CssNamedColor("lightslategray", "#778899");
  static lightslategrey = new CssNamedColor("lightslategrey", "#778899");
  static lightsteelblue = new CssNamedColor("lightsteelblue", "#b0c4de");
  static lightyellow = new CssNamedColor("lightyellow", "#ffffe0");
  static lime = new CssNamedColor("lime", "#00ff00");
  static limegreen = new CssNamedColor("limegreen", "#32cd32");
  static linen = new CssNamedColor("linen", "#faf0e6");
  static magenta = new CssNamedColor("magenta", "#ff00ff");
  static maroon = new CssNamedColor("maroon", "#800000");
  static mediumaquamarine = new CssNamedColor("mediumaquamarine", "#66cdaa");
  static mediumblue = new CssNamedColor("mediumblue", "#0000cd");
  static mediumorchid = new CssNamedColor("mediumorchid", "#ba55d3");
  static mediumpurple = new CssNamedColor("mediumpurple", "#9370db");
  static mediumseagreen = new CssNamedColor("mediumseagreen", "#3cb371");
  static mediumslateblue = new CssNamedColor("mediumslateblue", "#7b68ee");
  static mediumspringgreen = new CssNamedColor("mediumspringgreen", "#00fa9a");
  static mediumturquoise = new CssNamedColor("mediumturquoise", "#48d1cc");
  static mediumvioletred = new CssNamedColor("mediumvioletred", "#c71585");
  static midnightblue = new CssNamedColor("midnightblue", "#191970");
  static mintcream = new CssNamedColor("mintcream", "#f5fffa");
  static mistyrose = new CssNamedColor("mistyrose", "#ffe4e1");
  static moccasin = new CssNamedColor("moccasin", "#ffe4b5");
  static navajowhite = new CssNamedColor("navajowhite", "#ffdead");
  static navy = new CssNamedColor("navy", "#000080");
  static oldlace = new CssNamedColor("oldlace", "#fdf5e6");
  static olive = new CssNamedColor("olive", "#808000");
  static olivedrab = new CssNamedColor("olivedrab", "#6b8e23");
  static orange = new CssNamedColor("orange", "#ffa500");
  static orangered = new CssNamedColor("orangered", "#ff4500");
  static orchid = new CssNamedColor("orchid", "#da70d6");
  static palegoldenrod = new CssNamedColor("palegoldenrod", "#eee8aa");
  static palegreen = new CssNamedColor("palegreen", "#98fb98");
  static paleturquoise = new CssNamedColor("paleturquoise", "#afeeee");
  static palevioletred = new CssNamedColor("palevioletred", "#db7093");
  static papayawhip = new CssNamedColor("papayawhip", "#ffefd5");
  static peachpuff = new CssNamedColor("peachpuff", "#ffdab9");
  static peru = new CssNamedColor("peru", "#cd853f");
  static pink = new CssNamedColor("pink", "#ffc0cb");
  static plum = new CssNamedColor("plum", "#dda0dd");
  static powderblue = new CssNamedColor("powderblue", "#b0e0e6");
  static purple = new CssNamedColor("purple", "#800080");
  static rebeccapurple = new CssNamedColor("rebeccapurple", "#663399");
  static red = new CssNamedColor("red", "#ff0000");
  static rosybrown = new CssNamedColor("rosybrown", "#bc8f8f");
  static royalblue = new CssNamedColor("royalblue", "#4169e1");
  static saddlebrown = new CssNamedColor("saddlebrown", "#8b4513");
  static salmon = new CssNamedColor("salmon", "#fa8072");
  static sandybrown = new CssNamedColor("sandybrown", "#f4a460");
  static seagreen = new CssNamedColor("seagreen", "#2e8b57");
  static seashell = new CssNamedColor("seashell", "#fff5ee");
  static sienna = new CssNamedColor("sienna", "#a0522d");
  static silver = new CssNamedColor("silver", "#c0c0c0");
  static skyblue = new CssNamedColor("skyblue", "#87ceeb");
  static slateblue = new CssNamedColor("slateblue", "#6a5acd");
  static slategray = new CssNamedColor("slategray", "#708090");
  static slategrey = new CssNamedColor("slategrey", "#708090");
  static snow = new CssNamedColor("snow", "#fffafa");
  static springgreen = new CssNamedColor("springgreen", "#00ff7f");
  static steelblue = new CssNamedColor("steelblue", "#4682b4");
  static tan = new CssNamedColor("tan", "#d2b48c");
  static teal = new CssNamedColor("teal", "#008080");
  static thistle = new CssNamedColor("thistle", "#d8bfd8");
  static tomato = new CssNamedColor("tomato", "#ff6347");
  static turquoise = new CssNamedColor("turquoise", "#40e0d0");
  static violet = new CssNamedColor("violet", "#ee82ee");
  static wheat = new CssNamedColor("wheat", "#f5deb3");
  static white = new CssNamedColor("white", "#ffffff");
  static whitesmoke = new CssNamedColor("whitesmoke", "#f5f5f5");
  static yellow = new CssNamedColor("yellow", "#ffff00");
  static yellowgreen = new CssNamedColor("yellowgreen", "#9acd32");

  constructor(readonly colorname: string, readonly colorvalue: string) {
    super(colorname);
  }

  /**
   * get the named css with value
   * @param value
   */
  static getWithValue(value: string): CssNamedColor {
    return this.all.find((i) => {
      return i.colorvalue == value;
    });
  }

  static all = [
    CssNamedColor.aliceblue,
    CssNamedColor.antiquewhite,
    CssNamedColor.aqua,
    CssNamedColor.aquamarine,
    CssNamedColor.azure,
    CssNamedColor.beige,
    CssNamedColor.bisque,
    CssNamedColor.black,
    CssNamedColor.blanchedalmond,
    CssNamedColor.blue,
    CssNamedColor.blueviolet,
    CssNamedColor.brown,
    CssNamedColor.burlywood,
    CssNamedColor.cadetblue,
    CssNamedColor.chartreuse,
    CssNamedColor.chocolate,
    CssNamedColor.coral,
    CssNamedColor.cornflowerblue,
    CssNamedColor.cornsilk,
    CssNamedColor.crimson,
    CssNamedColor.cyan,
    CssNamedColor.darkblue,
    CssNamedColor.darkcyan,
    CssNamedColor.darkgoldenrod,
    CssNamedColor.darkgray,
    CssNamedColor.darkgreen,
    CssNamedColor.darkgrey,
    CssNamedColor.darkkhaki,
    CssNamedColor.darkmagenta,
    CssNamedColor.darkolivegreen,
    CssNamedColor.darkorange,
    CssNamedColor.darkorchid,
    CssNamedColor.darkred,
    CssNamedColor.darksalmon,
    CssNamedColor.darkseagreen,
    CssNamedColor.darkslateblue,
    CssNamedColor.darkslategray,
    CssNamedColor.darkslategrey,
    CssNamedColor.darkturquoise,
    CssNamedColor.darkviolet,
    CssNamedColor.deeppink,
    CssNamedColor.deepskyblue,
    CssNamedColor.dimgray,
    CssNamedColor.dimgrey,
    CssNamedColor.dodgerblue,
    CssNamedColor.firebrick,
    CssNamedColor.floralwhite,
    CssNamedColor.forestgreen,
    CssNamedColor.fuchsia,
    CssNamedColor.gainsboro,
    CssNamedColor.ghostwhite,
    CssNamedColor.goldenrod,
    CssNamedColor.gold,
    CssNamedColor.gray,
    CssNamedColor.green,
    CssNamedColor.greenyellow,
    CssNamedColor.grey,
    CssNamedColor.honeydew,
    CssNamedColor.hotpink,
    CssNamedColor.indianred,
    CssNamedColor.indigo,
    CssNamedColor.ivory,
    CssNamedColor.khaki,
    CssNamedColor.lavenderblush,
    CssNamedColor.lavender,
    CssNamedColor.lawngreen,
    CssNamedColor.lemonchiffon,
    CssNamedColor.lightblue,
    CssNamedColor.lightcoral,
    CssNamedColor.lightcyan,
    CssNamedColor.lightgoldenrodyellow,
    CssNamedColor.lightgray,
    CssNamedColor.lightgreen,
    CssNamedColor.lightgrey,
    CssNamedColor.lightpink,
    CssNamedColor.lightsalmon,
    CssNamedColor.lightseagreen,
    CssNamedColor.lightskyblue,
    CssNamedColor.lightslategray,
    CssNamedColor.lightslategrey,
    CssNamedColor.lightsteelblue,
    CssNamedColor.lightyellow,
    CssNamedColor.lime,
    CssNamedColor.limegreen,
    CssNamedColor.linen,
    CssNamedColor.magenta,
    CssNamedColor.maroon,
    CssNamedColor.mediumaquamarine,
    CssNamedColor.mediumblue,
    CssNamedColor.mediumorchid,
    CssNamedColor.mediumpurple,
    CssNamedColor.mediumseagreen,
    CssNamedColor.mediumslateblue,
    CssNamedColor.mediumspringgreen,
    CssNamedColor.mediumturquoise,
    CssNamedColor.mediumvioletred,
    CssNamedColor.midnightblue,
    CssNamedColor.mintcream,
    CssNamedColor.mistyrose,
    CssNamedColor.moccasin,
    CssNamedColor.navajowhite,
    CssNamedColor.navy,
    CssNamedColor.oldlace,
    CssNamedColor.olive,
    CssNamedColor.olivedrab,
    CssNamedColor.orange,
    CssNamedColor.orangered,
    CssNamedColor.orchid,
    CssNamedColor.palegoldenrod,
    CssNamedColor.palegreen,
    CssNamedColor.paleturquoise,
    CssNamedColor.palevioletred,
    CssNamedColor.papayawhip,
    CssNamedColor.peachpuff,
    CssNamedColor.peru,
    CssNamedColor.pink,
    CssNamedColor.plum,
    CssNamedColor.powderblue,
    CssNamedColor.purple,
    CssNamedColor.rebeccapurple,
    CssNamedColor.red,
    CssNamedColor.rosybrown,
    CssNamedColor.royalblue,
    CssNamedColor.saddlebrown,
    CssNamedColor.salmon,
    CssNamedColor.sandybrown,
    CssNamedColor.seagreen,
    CssNamedColor.seashell,
    CssNamedColor.sienna,
    CssNamedColor.silver,
    CssNamedColor.skyblue,
    CssNamedColor.slateblue,
    CssNamedColor.slategray,
    CssNamedColor.slategrey,
    CssNamedColor.snow,
    CssNamedColor.springgreen,
    CssNamedColor.steelblue,
    CssNamedColor.tan,
    CssNamedColor.teal,
    CssNamedColor.thistle,
    CssNamedColor.tomato,
    CssNamedColor.turquoise,
    CssNamedColor.violet,
    CssNamedColor.wheat,
    CssNamedColor.white,
    CssNamedColor.whitesmoke,
    CssNamedColor.yellow,
    CssNamedColor.yellowgreen,
  ];
}
