// !! Do not change the keynames
/**
 * static keywords and tokens based on typesciprt.
 */
export enum KeywordAndTokenStatic {
  /**
   * this is not a standard token. this does not exists on ast.
   * it's exceptionally present only for final formatting.
   */
  BreakSpaceToken = " ",
  /**
   * this is not a standard token. this does not exists on ast.
   * it's exceptionally present only for final formatting.
   */
  BreakLineToken = "\n",
  EndOfFileToken = "\n\n",
  OpenBraceToken = "{",
  CloseBraceToken = "}",
  OpenParenToken = "(",
  CloseParenToken = ")",
  OpenBracketToken = "[",
  CloseBracketToken = "]",
  DotToken = ".",
  DotDotDotToken = "...",
  SemicolonToken = ";",
  CommaToken = ",",
  QuestionDotToken = "?.",
  LessThanToken = "<",
  LessThanSlashToken = "</",
  GreaterThanToken = ">",
  SlashGreaterThanToken = "/>",
  LessThanEqualsToken = "<=",
  GreaterThanEqualsToken = ">=",
  EqualsEqualsToken = "==",
  ExclamationEqualsToken = "!=",
  EqualsEqualsEqualsToken = "===",
  ExclamationEqualsEqualsToken = "!==",
  EqualsGreaterThanToken = "=>",
  PlusToken = "+",
  MinusToken = "-",
  AsteriskToken = "*",
  AsteriskAsteriskToken = "**",
  SlashToken = "/",
  PercentToken = "%",
  PlusPlusToken = "++",
  MinusMinusToken = "--",
  LessThanLessThanToken = "<<",
  GreaterThanGreaterThanToken = ">>",
  GreaterThanGreaterThanGreaterThanToken = "<<<",
  AmpersandToken = "&",
  BarToken = "|",
  CaretToken = "^",
  ExclamationToken = "!",
  TildeToken = "~",
  AmpersandAmpersandToken = "&&",
  BarBarToken = "||",
  QuestionToken = "?",
  ColonToken = ":",
  AtToken = "@",
  QuestionQuestionToken = "??",
  BacktickToken = "`",
  EqualsToken = "=",
  PlusEqualsToken = "+=",
  MinusEqualsToken = "-=",
  AsteriskEqualsToken = "*=",
  AsteriskAsteriskEqualsToken = "**=",
  SlashEqualsToken = "/=",
  PercentEqualsToken = "%=",
  LessThanLessThanEqualsToken = "<<=",
  GreaterThanGreaterThanEqualsToken = ">>=",
  GreaterThanGreaterThanGreaterThanEqualsToken = ">>>=",
  AmpersandEqualsToken = "&=",
  BarEqualsToken = "|=",
  BarBarEqualsToken = "||=",
  AmpersandAmpersandEqualsToken = "&&=",
  QuestionQuestionEqualsToken = "??=",
  CaretEqualsToken = "^=",

  // keywords
  BreakKeyword = "break",
  CaseKeyword = "case",
  CatchKeyword = "catch",
  ClassKeyword = "class",
  ConstKeyword = "const",
  ContinueKeyword = "continue",
  DebuggerKeyword = "debugger",
  DefaultKeyword = "default",
  DeleteKeyword = "delete",
  DoKeyword = "dot",
  ElseKeyword = "else",
  EnumKeyword = "enum",
  ExportKeyword = "export",
  ExtendsKeyword = "extends",
  FalseKeyword = "false",
  FinallyKeyword = "finally",
  ForKeyword = "for",
  FunctionKeyword = "function",
  IfKeyword = "if",
  ImportKeyword = "import",
  InKeyword = "in",
  InstanceOfKeyword = "instanceof",
  NewKeyword = "new",
  NullKeyword = "null",
  ReturnKeyword = "return",
  SuperKeyword = "super",
  SwitchKeyword = "switch",
  ThisKeyword = "this",
  ThrowKeyword = "throw",
  TrueKeyword = "true",
  TryKeyword = "try",
  TypeOfKeyword = "typeof",
  VarKeyword = "var",
  VoidKeyword = "void",
  WhileKeyword = "while",
  WithKeyword = "with",
  ImplementsKeyword = "implements",
  InterfaceKeyword = "interface",
  LetKeyword = "let",
  PackageKeyword = "package",
  PrivateKeyword = "private",
  ProtectedKeyword = "protected",
  PublicKeyword = "public",
  StaticKeyword = "static",
  YieldKeyword = "yield",
  AbstractKeyword = "abstract",
  AsKeyword = "as",
  AssertsKeyword = "assert",
  AnyKeyword = "any",
  AsyncKeyword = "async",
  AwaitKeyword = "await",
  BooleanKeyword = "boolean",
  ConstructorKeyword = "constructor",
  DeclareKeyword = "declare",
  GetKeyword = "get",
  InferKeyword = "infer",
  IntrinsicKeyword = "intrinsic",
  IsKeyword = "is",
  KeyOfKeyword = "keyof",
  ModuleKeyword = "module",
  NamespaceKeyword = "namespace",
  NeverKeyword = "never",
  ReadonlyKeyword = "readonly",
  RequireKeyword = "require",
  NumberKeyword = "number",
  ObjectKeyword = "object",
  SetKeyword = "set",
  StringKeyword = "string",
  SymbolKeyword = "symbol",
  TypeKeyword = "type",
  UndefinedKeyword = "undefined",
  UniqueKeyword = "unique",
  UnknownKeyword = "unknown",
  FromKeyword = "from",
  GlobalKeyword = "global",
  BigIntKeyword = "bigint",
  OverrideKeyword = "override",
  OfKeyword = "of",
}
